version: '3'

services:
  your-app:
    image: shahabajmal/automatic-time-tablegenerator:pro # Replace with the name you want for your Docker image
    container_name: Timetable_DataSheet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - ASPNETCORE_ENVIRONMENT=DevStaging
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - db-host=sql-server
    depends_on:
      - sql-server

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: SQLServer
    ports:
      - '1433:1433'
    environment:
      MSSQL_SA_PASSWORD: umair@123
      ACCEPT_EULA: Y
